// <auto-generated />
using System;
using FuzzyDataDbCore.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuzzyDataDbCore.Migrations
{
    [DbContext(typeof(FuzzyDataDbContext))]
    [Migration("20250301114147_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuzzyDataDbCore.Models.CustomLinguisticVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("creator_name");

                    b.Property<int>("CubeSliceId")
                        .HasColumnType("int");

                    b.Property<int>("FuncId")
                        .HasColumnType("int");

                    b.Property<string>("MeasureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MinIndex")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomLinguisticVariables");
                });

            modelBuilder.Entity("FuzzyDataDbCore.Models.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("creator_name");

                    b.Property<int>("CustomLinguisticVariableId")
                        .HasColumnType("int");

                    b.Property<int>("PointSeq")
                        .HasColumnType("int");

                    b.Property<double>("XValue")
                        .HasColumnType("float")
                        .HasColumnName("x_value");

                    b.Property<double>("YValue")
                        .HasColumnType("float")
                        .HasColumnName("y_value");

                    b.HasKey("Id");

                    b.HasIndex("CustomLinguisticVariableId");

                    b.ToTable("Point");
                });

            modelBuilder.Entity("FuzzyDataDbCore.Models.Point", b =>
                {
                    b.HasOne("FuzzyDataDbCore.Models.CustomLinguisticVariable", "CustomLinguisticVariable")
                        .WithMany("Points")
                        .HasForeignKey("CustomLinguisticVariableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomLinguisticVariable");
                });

            modelBuilder.Entity("FuzzyDataDbCore.Models.CustomLinguisticVariable", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
